### ISSUE TITLE
Memcached TimeOut Exception

### ISSUE THREAD

**Issue by skathir1** [killme2008/xmemcached#105]
Getting following exception while set,add,delete and get , I am using xmemcached-1.3.8.jar. Please let me know below issue is fixed in latest version of xmemcached?

java.util.concurrent.TimeoutException: Timed out(200) waiting for operation
	at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2565)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2548)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1312)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1370)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1357)

**Comment by 632677663** [comment]
Same question

**Comment by indiketa** [comment]
+1 Under high concurrency (22K users) sometimes:
java.util.concurrent.TimeoutException: Timed out(5000 milliseconds) waiting for operation while connected to 10.0.10.172:11211
	at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2577) ~[xmemcached-2.4.2.jar:?]

(retrieving a simple token string)

**Comment by yinghuzhu** [comment]
> +1 Under high concurrency (22K users) sometimes: java.util.concurrent.TimeoutException: Timed out(5000 milliseconds) waiting for operation while connected to 10.0.10.172:11211 at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2577) ~[xmemcached-2.4.2.jar:?]
> 
> (retrieving a simple token string)

did you solve this issue ? how did you solve if os ?

**Comment by yinghuzhu** [comment]
> +1 Under high concurrency (22K users) sometimes: java.util.concurrent.TimeoutException: Timed out(5000 milliseconds) waiting for operation while connected to 10.0.10.172:11211 at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2577) ~[xmemcached-2.4.2.jar:?]
> 
> (retrieving a simple token string)

@indiketa Did you solve this issue ? how did you solve if so ?
