### ISSUE TITLE
Null pointer exception when doing multi key get

### ISSUE THREAD

**Issue by dzhdhr** [killme2008/xmemcached#146]
Hi, when I try to run some benchmark for multi-get to get 100 key at a time. Sometime I get Nullpointer exception. The error trace look like follow: 
```
java.lang.NullPointerException
        at net.rubyeye.xmemcached.XMemcachedClient.reduceResult(XMemcachedClient.java:1215)
        at net.rubyeye.xmemcached.XMemcachedClient.getMulti0(XMemcachedClient.java:1202)
        at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1088)
        at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1121)
        at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1110)
        at MemcachedMultiGetTest.cacheMultiGet(MemcachedMultiGetTest.java:29)
```
And the code is follow:
```
int n = 100;
List<String> keys = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            keys.add(Main.createKeyName(prefix, i));
        }
Map<String,Object> result= client.get(keys);
```
where I was trying to get 100 key at a time.
Any hint on how to fix this.

Thank.

**Comment by hopi** [comment]
Hi, this PR https://github.com/killme2008/xmemcached/pull/145 will solve the problem.

**Comment by killme2008** [comment]
Good job! Thank you.
