### ISSUE TITLE
Session(127.0.0.1:11211) has been closed

### ISSUE THREAD

**Issue by imacback** [killme2008/xmemcached#34]
最近使用老是报这个错，一样的程序在其他2台服务器正常，关键是出问题的服务器启动的时候，有的set是成功的，有的set报这个错，找不到啥原因了。
lt :true -- com.ydqt.pay.common.cache.CacheManager.doAccessCheck(CacheManager.java:165)
net.rubyeye.xmemcached.exception.MemcachedException: Session(127.0.0.1:11211) has been closed
        at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:506)
        at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
        at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2496)
        at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1338)
        at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1396)
        at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1383)
        at com.ydqt.pay.common.cache.XmemcachedUtil.set(XmemcachedUtil.java:90)
        at com.ydqt.pay.common.cache.CacheManager.doAccessCheck(CacheManager.java:164)
        at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at $Proxy39.loadUserTotalMonthLimitInfo(Unknown Source)
        at com.ydqt.pay.core.job.CacheJob.work_UserTotalMonthLimit(CacheJob.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
2015-06-24 11:31:47 INFO  put key: {api_CacheServiceImpl_loadUserTotalMonthLimitInfo_-530343884},obj: {{460036130191220=999999900, 460078116640833=999996500}},result :false -- com.ydqt.pay.common.cache.CacheManager.doAccessCheck(CacheManager.java:165)
2015-06-24 11:31:47 INFO  put key: {api_CacheServiceImpl_loadAisleMonthLimitInfo_-422391745},obj: {{1=96600}},result :true 

上面一条是报错的，但下面一条又正常了。。。

**Comment by imacback** [comment]
已解决，设置  builder.setFailureMode(false); 
查看到源代码：
if (this.failureMode) {
			List<Session> sessionList = this
					.getStandbySessionListByMainNodeAddr(session
							.getRemoteSocketAddress());
			if (sessionList != null && !sessionList.isEmpty()) {
				return (MemcachedTCPSession) sessionList.get(this.random
						.nextInt(sessionList.size()));
			}
		}

但是不知道为啥session会关闭呢？

**Comment by killme2008** [comment]
看起来是网络瞬断引起的链接关闭又重连。
