### ISSUE TITLE
 XMemcached network layou t exception

### ISSUE THREAD

**Issue by 2305049078** [killme2008/xmemcached#43]
Help ~~
My xmemcached ver is 1.3.5.
I got this  error msg:
2016-02-11 06:31:59,912 [xmemcached-read-thread-1-thread-4] ERROR n.r.xmemcached.impl.MemcachedHandler 111 - XMemcached network layou
t exception
java.lang.OutOfMemoryError: Java heap space
        at java.lang.String.substring(String.java:1939) ~[na:1.6.0_45]
        at java.lang.String.subSequence(String.java:1972) ~[na:1.6.0_45]
        at java.util.regex.Pattern.split(Pattern.java:1002) ~[na:1.6.0_45]
        at java.lang.String.split(String.java:2292) ~[na:1.6.0_45]
        at java.lang.String.split(String.java:2334) ~[na:1.6.0_45]
        at net.rubyeye.xmemcached.command.text.TextVersionCommand.decode(TextVersionCommand.java:66) ~[xmemcached-1.3.5.jar:na]
        at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode0(MemcachedDecoder.java:61) ~[xmemcached-1.3.5.jar:na]
        at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode(MemcachedDecoder.java:56) ~[xmemcached-1.3.5.jar:na]
        at com.google.code.yanf4j.nio.impl.NioTCPSession.decode(NioTCPSession.java:288) ~[xmemcached-1.3.5.jar:na]
        at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:205) ~[xmemcached-1.3.5.jar:na]
        at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:198) [xmemcached-1.3.5.jar:na]
        at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:343) [xmemcached-1.3.5.jar:na]
        at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56) [xmemcached-1.3
.5.jar:na]
        at com.google.code.yanf4j.nio.impl.NioController$ReadTask.run(NioController.java:110) [xmemcached-1.3.5.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

**Comment by killme2008** [comment]
```
java.lang.OutOfMemoryError: Java heap space
```

You had ran your application out of memory,maybe it is a memory leak in your app or JVM heap size is too small.

NOTE ** you should use xmemcached client as a singleton object**
