### ISSUE TITLE
Heal-Session-Thread stops if UnresolvedAddressException occurs

### ISSUE THREAD

**Issue by srpgers** [killme2008/xmemcached#53]
If a network issue occurs and hostnames cannot be resolved, then the SessionMonitor throws an exception (in rescheduleConnectRequest in the log line) and so the thread stops.
After that the XMemcachedClient becomes unusable an never re-connects.

`Exception in thread "Heal-Session-Thread" java.lang.NullPointerException
	at net.rubyeye.xmemcached.impl.MemcachedConnector$SessionMonitor.rescheduleConnectRequest(MemcachedConnector.java:166)
	at net.rubyeye.xmemcached.impl.MemcachedConnector$SessionMonitor.run(MemcachedConnector.java:152)`
After earlier exception
`[13:43:40,544][] [ERROR]xmemcached.impl.MemcachedConnector$SessionMonitor:151 - SessionMonitor connect error
java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:123)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at net.rubyeye.xmemcached.impl.MemcachedConnector.connect(MemcachedConnector.java:468)
	at net.rubyeye.xmemcached.impl.MemcachedConnector$SessionMonitor.run(MemcachedConnector.java:118)`

With the code
`log.error("Reconnect to " + address.getAddress().getHostAddress() + ":" + address.getPort() + " fail");`
Because address.getAddress() returns null as host not resolvable.

**Comment by killme2008** [comment]
Thanks, it's a serious issue, i should fix it and release a new version ASAP.

**Comment by srpgers** [comment]
FYI - Changed locally to be
`log.error("Reconnect to " + address + " fail");`
And works a treat.

**Comment by killme2008** [comment]
Released 2.3.0, but it may take sometime to be synchronized to maven central repository.

https://github.com/killme2008/xmemcached/releases/tag/xmemcached-2.3.0
