### ISSUE TITLE
Failover mode cannot be initialized

### ISSUE THREAD

**Issue by ferenctoth75** [killme2008/xmemcached#73]
Hi!

In 2.4.0 when trying to use failover mode (builder.setFailureMode(true);) and specifying two memcached instances comma separated for the builder, the builder.build() call will fail with the following error:

java.lang.ClassCastException: net.rubyeye.xmemcached.impl.ClosedMemcachedTCPSession cannot be cast to net.rubyeye.xmemcached.networking.MemcachedSession
        at net.rubyeye.xmemcached.impl.MemcachedConnector.addSession(MemcachedConnector.java:227)
        at net.rubyeye.xmemcached.XMemcachedClient.connect(XMemcachedClient.java:621)
        at net.rubyeye.xmemcached.XMemcachedClient.<init>(XMemcachedClient.java:880)
        at net.rubyeye.xmemcached.XMemcachedClientBuilder.build(XMemcachedClientBuilder.java:339)

**Comment by killme2008** [comment]
Yep, it's an issue, it sees that your memcached servers were down when creating the memcached client.

I will fix it ASAP.

**Comment by killme2008** [comment]
Released 2.4.2, it may takes sometime to be synced into maven central repo.

https://github.com/killme2008/xmemcached/releases/tag/xmemcached-2.4.2

**Comment by ferenctoth75** [comment]
Thanks a lot!
